import { supabase } from "../supabase.js";

const $ = (id) => document.getElementById(id);
const qs = (selector, root = document) => root.querySelector(selector);
const qsa = (selector, root = document) => [...root.querySelectorAll(selector)];
let session = null;
let account = null;
let authMode = "signin";

function messageText(value) { if(typeof value==="string") return value; if(value?.message && typeof value.message==="string") return value.message; if(value?.error && typeof value.error==="string") return value.error; if(value && typeof value==="object"){ try{ const nested=value.message||value.error||value.data?.message||value.data?.error; if(typeof nested==="string") return nested; return JSON.stringify(value); }catch{} } return String(value||"Something went wrong."); }
function safeMessage(error) { const message=messageText(error); if(/invalid login credentials/i.test(message))return "Email or password is incorrect."; if(/email not confirmed/i.test(message))return "Please confirm your email before signing in."; if(/already registered|already exists/i.test(message))return "That email is already registered. Try signing in."; if(/password/i.test(message)&&/6/i.test(message))return "Password must be at least 6 characters."; return message.length>180?"Unable to complete that request right now.":message; }
function setAuthStatus(message="",type=""){const el=$("authStatus");el.textContent=message;el.className=`form-status ${type}`.trim();}
function toast(message){const el=$("toast");const safe=messageText(message);el.textContent=safe;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2600);}
function setAuthMode(mode){authMode=mode;const signIn=mode==="signin";$("signInTab").classList.toggle("active",signIn);$("signUpTab").classList.toggle("active",!signIn);$("signInBtn").classList.toggle("hidden",!signIn);$("signUpBtn").classList.toggle("hidden",signIn);$("forgotBtn").classList.toggle("hidden",!signIn);$("authPassword").autocomplete=signIn?"current-password":"new-password";setAuthStatus("");}
async function authAction(kind){const email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value;if(!email||!email.includes("@"))return setAuthStatus("Enter a valid email address.","error");if(password.length<6)return setAuthStatus("Password must be at least 6 characters.","error");$("signInBtn").disabled=true;$("signUpBtn").disabled=true;setAuthStatus(kind==="signin"?"Signing in…":"Creating your account…");try{const result=kind==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)throw result.error;if(kind==="signup"&&!result.data.session){setAuthStatus("Account created. Check your email if confirmation is required, then sign in.","success");setAuthMode("signin");$("authPassword").value="";return;}await loadSession();}catch(error){console.error("OBITREND auth error:",error);setAuthStatus(safeMessage(error),"error");}finally{$("signInBtn").disabled=false;$("signUpBtn").disabled=false;}}
async function resetPassword(){const email=$("authEmail").value.trim().toLowerCase();if(!email||!email.includes("@"))return setAuthStatus("Enter your email first.","error");try{const redirectTo=window.location.origin+window.location.pathname;const result=await supabase.auth.resetPasswordForEmail(email,{redirectTo});if(result.error)throw result.error;setAuthStatus("Password reset instructions sent to your email.","success");}catch(error){setAuthStatus(safeMessage(error),"error");}}
async function loadSession(){const result=await supabase.auth.getSession();if(result.error){console.error(result.error);showAuth();return;}session=result.data.session||null;if(!session){showAuth();return;}showDashboard();await loadAccount();await verifyReturnedPayment();}
async function loadAccount(){if(!session?.access_token)return;try{const response=await fetch("/api/account",{method:"GET",headers:{Accept:"application/json",Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok||!data?.ok)throw new Error(data?.error||"Unable to load your account.");account=data.account;renderAccount();}catch(error){console.error("OBITREND account error:",error);account={user:{email:session.user?.email||"",obitrendUserId:""},imageCredits:{free:0,freeTotal:3,pro:0,proTotal:0,available:0},pro:{active:false,planName:null,credits:0},video:{seconds:0}};renderAccount();toast("Signed in. Account details are still loading.");}}
function renderAccount(){const user=account?.user||{},images=account?.imageCredits||{},pro=account?.pro||{},video=account?.video||{},email=user.email||session?.user?.email||"Creator",letter=email.charAt(0).toUpperCase()||"O",proCredits=Number(images.pro||0),freeCredits=Number(images.free||0),available=pro.active?proCredits:Math.max(0,freeCredits),videoSeconds=Number(video.seconds||0);$("profileName").textContent=email.split("@")[0]||"Creator";$("avatarLetter").textContent=letter;$("accountAvatar").textContent=letter;$("accountEmail").textContent=email;$("accountId").textContent=user.obitrendUserId||"Authenticated OBITREND account";$("accountLocation").textContent=[user.city,user.country].filter(Boolean).join(", ")||"Profile location not set";$("homeImageCredits").textContent=available;$("homeVideoSeconds").textContent=videoSeconds;$("homePlan").textContent=pro.active?(pro.planName||"Pro"):"Free";$("homeExpiry").textContent=pro.active&&pro.expiresAt?formatExpiry(pro.expiresAt):"No active Pro plan";$("creditsAvailable").textContent=available;$("creditsPro").textContent=Number(images.pro||0);$("creditsVideo").textContent=videoSeconds;$("videoSecondsLarge").textContent=`${videoSeconds} seconds`;$("sidePlan").textContent=pro.active?(pro.planName||"Pro"):"Free";$("sideCredits").textContent=`${available} image credit${available===1?"":"s"}`;}
function formatExpiry(timestamp){const value=Number(timestamp);if(!Number.isFinite(value))return "Active Pro plan";const date=new Date(value<1e12?value*1000:value);if(Number.isNaN(date.getTime()))return "Active Pro plan";return `Expires ${date.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}`;}
function showAuth(){$("authScreen").classList.remove("hidden");$("dashboardScreen").classList.add("hidden");}
function showDashboard(){$("authScreen").classList.add("hidden");$("dashboardScreen").classList.remove("hidden");openPage("create");}
function openPage(page){window.scrollTo({top:0,behavior:"instant"});const valid=["home","create","gallery","video","credits","account"];if(!valid.includes(page))page="home";qsa(".page").forEach(el=>el.classList.remove("active-page"));$(`page${page.charAt(0).toUpperCase()}${page.slice(1)}`).classList.add("active-page");qsa(".nav-item").forEach(el=>el.classList.toggle("active",el.dataset.page===page));const titles={home:"Dashboard",create:"Create",gallery:"Gallery",video:"Video AI",credits:"Credits",account:"Account"};$("pageTitle").textContent=titles[page];$("pageKicker").textContent=page==="home"?"WORKSPACE":page.toUpperCase();closeSidebar();}
function openSidebar(){$("sidebar").classList.add("open");$("overlay").classList.add("open");}function closeSidebar(){$("sidebar").classList.remove("open");$("overlay").classList.remove("open");}

/* =====================================================
   CONVERSATIONAL CREATIVE FLOW
===================================================== */
let sketchTimer=null;
function addUserMessage(text){const wrap=document.createElement("div");wrap.className="chat-card user-card";wrap.innerHTML=`<div class="chat-label">YOU</div><p></p>`;wrap.querySelector("p").textContent=text;$("chatMessages").appendChild(wrap);wrap.scrollIntoView({behavior:"smooth",block:"nearest"});}
function renderSketchDots(progress){const canvas=$("dotCanvas");if(!canvas)return;canvas.innerHTML="";const cols=11,rows=6,cx=5,cy=2.5;for(let y=0;y<rows;y++){for(let x=0;x<cols;x++){const d=Math.hypot((x-cx)/1.7,(y-cy)/1.15);const wave=(progress/100)*7;const active=d<1.15+wave*.18||((x+y*3+Math.floor(progress/8))%9===0&&d<3.5);const dot=document.createElement("i");dot.className=active?"dot active":"dot";dot.style.setProperty("--d",Math.min(d,4));dot.style.animationDelay=((x+y)%7)*45+"ms";canvas.appendChild(dot);}}}
function startSketch(){clearInterval(sketchTimer);return new Promise(resolve=>{const card=$("sketchCard"),pct=$("progressText");card.classList.remove("hidden");let progress=0;pct.textContent="0%";renderSketchDots(0);sketchTimer=setInterval(()=>{progress+=Math.floor(Math.random()*7)+3;if(progress>100)progress=100;pct.textContent=progress+"%";renderSketchDots(progress);if(progress>=100){clearInterval(sketchTimer);resolve();}},260);});}
async function handleCreative(){const typedPrompt=$("creativePrompt").value.trim();const previousUserPrompt=qsa(".user-card p",$("chatMessages")).at(-1)?.textContent?.trim()||"";const prompt=typedPrompt||previousUserPrompt;const file=$("garmentInput")?.files?.[0];if(!prompt)return toast("Describe the fashion image first.");if(!session?.access_token)return toast("Please sign in before generating.");if(file&&file.size>9*1024*1024)return toast("Garment image is too large. Use an image under 9 MB.");const availableCredits=Number(account?.imageCredits?.available||0);if(availableCredits<=0){toast("Your free generations are finished. Upgrade to OBITREND Pro to continue.");return;}addUserMessage(prompt);$("creativePrompt").value="";const button=$("generateCreativeBtn"),status=$("sketchStatus");button.disabled=true;try{const preview=file?( $("garmentInput").dataset.preview||await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);}) ):null;await startSketch();const monthly=Boolean(account?.pro?.active&&String(account?.pro?.planName||"").toUpperCase().includes("MONTHLY"));const payload={userId:session.user.id,prompt,creativeDirection:prompt,clothingPreservation:Boolean(file),photorealistic:true,realCamera:true,garmentReference:Boolean(file),imageCount:1,monthlyPro:monthly,monthlyProAccess:monthly,plan:account?.pro?.planName||null,planTier:account?.pro?.active?"pro":"free"};if(file)payload.imageBase64=preview;status.textContent="Generating your photorealistic fashion image…";const response=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{}if(!response.ok)throw new Error(messageText(data?.error||data?.message)||`Generation failed (${response.status}).`);const image=data?.imageUrl||data?.image||data?.images?.[0]||data?.data?.imageUrl||data?.data?.images?.[0];if(!image)throw new Error("The image engine completed without returning an image.");$("creativeResultImage").src=image;$("creativeResult").classList.remove("hidden");$("creativeResultStatus").textContent="Your OBITREND image is ready.";$("downloadCreativeBtn").onclick=()=>{const a=document.createElement("a");a.href=image;a.download="OBITREND-fashion-campaign.png";a.target="_blank";a.rel="noopener";a.click();};toast("Image generated successfully.");$("creativeResult").scrollIntoView({behavior:"smooth",block:"start"});await loadAccount();}catch(error){console.error("OBITREND creative generation error:",error);status.textContent="Generation could not be completed.";toast(safeMessage(error));}finally{button.disabled=false;}}
function setupCreative(){const input=$("garmentInput"),name=$("garmentName"),prompt=$("creativePrompt"),button=$("generateCreativeBtn"),promptOnly=$("promptOnlyBtn");if(!input||!prompt||!button)return;input.addEventListener("change",()=>{const file=input.files?.[0];name.textContent=file?file.name:"No garment selected";if(file){const reader=new FileReader();reader.onload=()=>{input.dataset.preview=reader.result;};reader.readAsDataURL(file);toast("Garment ready for the studio.");}});qsa(".prompt-suggestion").forEach(b=>b.addEventListener("click",()=>{prompt.value=b.dataset.prompt||"";prompt.focus();}));button.addEventListener("click",handleCreative);promptOnly?.addEventListener("click",()=>{input.value="";delete input.dataset.preview;name.textContent="Prompt only • no garment";promptOnly.classList.add("active");toast("Prompt-only mode selected.");});prompt.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();handleCreative();}});}

$("signInTab").onclick=()=>setAuthMode("signin");$("signUpTab").onclick=()=>setAuthMode("signup");$("signInBtn").onclick=e=>{e.preventDefault();authAction("signin")};$("signUpBtn").onclick=e=>{e.preventDefault();authAction("signup")};$("forgotBtn").onclick=resetPassword;$("authForm").addEventListener("submit",e=>{e.preventDefault();authAction(authMode)});
qsa(".nav-item").forEach(button=>button.addEventListener("click",()=>openPage(button.dataset.page)));qsa("[data-page-jump]").forEach(button=>button.addEventListener("click",()=>openPage(button.dataset.pageJump)));qsa("[data-coming-soon]").forEach(button=>button.addEventListener("click",()=>toast(`${button.dataset.comingSoon} is the next build section.`)));const openVideoStudioBtn=$("openVideoStudioBtn");openVideoStudioBtn?.addEventListener("click",()=>{const launcher=$("obitrendVideoLauncher");if(launcher){launcher.click();return;}toast("Video studio is still loading. Try again in a moment.");});
$("menuBtn").onclick=openSidebar;$("overlay").onclick=closeSidebar;$("profileBtn").onclick=()=>openPage("account");$("signOutBtn").onclick=async()=>{try{const result=await supabase.auth.signOut();if(result.error)throw result.error;}catch(error){toast(safeMessage(error));return;}session=null;account=null;setAuthStatus("Signed out.","success");showAuth();};
supabase.auth.onAuthStateChange((_event,nextSession)=>{session=nextSession||null;if(session){showDashboard();loadAccount().then(verifyReturnedPayment);}else showAuth();});
setAuthMode("signin");setupCreative();loadSession();
async function startProPayment(plan){
  if(!session?.access_token)return toast("Please sign in before purchasing Pro.");
  const button=document.querySelector('.pay-pro-btn[data-plan="'+plan+'"]');
  if(button){button.disabled=true;button.dataset.originalText=button.textContent;button.textContent="Connecting to Paystack…";}
  try{
    const email=String(session.user?.email||account?.user?.email||"").trim().toLowerCase();
    const response=await fetch("/api/paystack",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({product:"OBITREND_PRO",plan,email})});
    const data=await response.json().catch(()=>({}));
    if(!response.ok||!data?.authorization_url)throw new Error(messageText(data?.error)||"Unable to start payment.");
    window.location.href=data.authorization_url;
  }catch(error){console.error("OBITREND payment error:",error);toast(safeMessage(error));if(button){button.disabled=false;button.textContent=button.dataset.originalText||"Continue to payment →";}}
}
async function verifyReturnedPayment(){
  const params=new URLSearchParams(window.location.search);
  const reference=params.get("reference")||params.get("trxref")||params.get("trx_ref");
  if(!reference||!session?.access_token)return;
  try{
    toast("Verifying your Paystack payment…");
    const response=await fetch("/api/paystack?reference="+encodeURIComponent(reference),{headers:{Accept:"application/json",Authorization:`Bearer ${session.access_token}`},cache:"no-store"});
    const data=await response.json().catch(()=>({}));
    if(!response.ok||!data?.ok)throw new Error(messageText(data?.error)||"Payment verification failed.");
    await loadAccount();
    toast(data?.duplicate?"Payment already applied.":"Payment confirmed. Your Pro credits are now available.");
    window.history.replaceState({},document.title,window.location.pathname);
    openPage("credits");
  }catch(error){console.error("OBITREND payment verification error:",error);toast(safeMessage(error));}
}
qsa(".pay-pro-btn").forEach(b=>b.addEventListener("click",()=>startProPayment(b.dataset.plan)));

qsa(".bottom-nav-item").forEach(button=>button.addEventListener("click",()=>{openPage(button.dataset.page);qsa(".bottom-nav-item").forEach(el=>el.classList.toggle("active",el===button));}));
