export default function handler(req, res) {
  const options = {
    model: [
      "Luxury lifestyle model",
      "Elegant fashion model",
      "African fashion model",
      "Editorial runway model",
      "High-fashion model",
      "Commercial fashion model",
      "Street style model",
      "Luxury campaign model",
      "Beauty campaign model",
      "Sports fashion model",
      "Resort fashion model",
      "Bridal fashion model",
      "Evening fashion model",
      "Urban fashion model",
      "Professional business model",
      "Casual lifestyle model",
      "Premium catalog model",
      "Influencer fashion model",
      "Magazine cover model",
      "Luxury travel model"
    ],

    body: [
      "Slim fashion model",
      "Curvy fashion model",
      "Athletic fashion model",
      "Petite fashion model",
      "Tall fashion model",
      "Plus-size fashion model",
      "Elegant feminine figure",
      "Hourglass fashion figure",
      "Fit athletic figure",
      "Natural body proportions",
      "Petite elegant figure",
      "Tall elegant figure"
    ],

    style: [
      "Luxury fashion",
      "Streetwear",
      "High fashion",
      "Editorial",
      "Casual chic",
      "Business fashion",
      "Evening glamour",
      "Resort fashion",
      "Beach fashion",
      "Sportswear",
      "Athleisure",
      "Wedding fashion",
      "Party fashion",
      "Urban fashion",
      "Minimalist fashion",
      "African luxury fashion",
      "Contemporary fashion",
      "Red carpet fashion",
      "Travel fashion",
      "Summer fashion",
      "Winter fashion",
      "Denim fashion",
      "Classic elegance",
      "Modern luxury"
    ],

    fashionStyle: [
      "Luxury fashion",
      "Streetwear",
      "High fashion",
      "Editorial",
      "Casual chic",
      "Business fashion",
      "Evening glamour",
      "Resort fashion",
      "Beach fashion",
      "Sportswear",
      "Athleisure",
      "Wedding fashion",
      "Party fashion",
      "Urban fashion",
      "Minimalist fashion",
      "African luxury fashion",
      "Contemporary fashion",
      "Red carpet fashion",
      "Travel fashion",
      "Summer fashion",
      "Winter fashion",
      "Denim fashion",
      "Classic elegance",
      "Modern luxury"
    ],

    pose: [
      "Walking naturally",
      "Standing confidently",
      "Luxury editorial pose",
      "Looking over shoulder",
      "Hands on waist",
      "One hand in pocket",
      "Relaxed standing pose",
      "Walking toward camera",
      "Walking away from camera",
      "Seated elegantly",
      "Leaning against wall",
      "Modeling beside vehicle",
      "Fashion runway pose",
      "Crossed-leg pose",
      "Natural candid pose",
      "Looking into distance",
      "Hair movement pose",
      "Full-body campaign pose",
      "Three-quarter fashion pose",
      "Magazine cover pose"
    ],

    country: [
      "Nigeria",
      "Ghana",
      "South Africa",
      "Egypt",
      "Kenya",
      "Morocco",
      "United States",
      "United Kingdom",
      "France",
      "Italy",
      "Spain",
      "United Arab Emirates",
      "Qatar",
      "Saudi Arabia",
      "Turkey",
      "Greece",
      "Brazil",
      "Canada",
      "Australia",
      "Japan",
      "South Korea",
      "Singapore",
      "Thailand",
      "Switzerland",
      "Germany"
    ],

    city: [
      "Lagos",
      "Abuja",
      "Port Harcourt",
      "Accra",
      "Johannesburg",
      "Cape Town",
      "Cairo",
      "Nairobi",
      "Marrakesh",
      "New York",
      "Los Angeles",
      "Miami",
      "Las Vegas",
      "London",
      "Paris",
      "Milan",
      "Rome",
      "Barcelona",
      "Dubai",
      "Abu Dhabi",
      "Doha",
      "Istanbul",
      "Athens",
      "Toronto",
      "Tokyo",
      "Seoul",
      "Singapore",
      "Sydney",
      "Zurich",
      "Berlin"
    ],

    environment: [
      "Luxury hotel",
      "Luxury hotel lobby",
      "Luxury hotel rooftop",
      "Luxury apartment",
      "Luxury mansion",
      "Modern villa",
      "Luxury compound",
      "Fashion boutique",
      "Shopping mall",
      "Designer store",
      "Premium restaurant",
      "Rooftop restaurant",
      "Coffee shop",
      "Beach resort",
      "Private beach",
      "Swimming pool",
      "Luxury playground",
      "Football stadium",
      "Basketball court",
      "Tennis court",
      "City street",
      "Luxury boulevard",
      "Downtown city",
      "Airport",
      "Private jet lounge",
      "Marina",
      "Park",
      "Garden",
      "Desert resort",
      "Mountain resort",
      "Nightclub",
      "Concert venue",
      "Fashion runway",
      "Photography studio",
      "Art gallery",
      "Museum",
      "University campus",
      "Modern office",
      "Business district"
    ],

    location: [
      "Luxury hotel",
      "Luxury hotel lobby",
      "Luxury hotel rooftop",
      "Luxury apartment",
      "Luxury mansion",
      "Modern villa",
      "Luxury compound",
      "Fashion boutique",
      "Shopping mall",
      "Designer store",
      "Premium restaurant",
      "Rooftop restaurant",
      "Coffee shop",
      "Beach resort",
      "Private beach",
      "Swimming pool",
      "Luxury playground",
      "Football stadium",
      "Basketball court",
      "Tennis court",
      "City street",
      "Luxury boulevard",
      "Downtown city",
      "Airport",
      "Private jet lounge",
      "Marina",
      "Park",
      "Garden",
      "Desert resort",
      "Mountain resort",
      "Nightclub",
      "Concert venue",
      "Fashion runway",
      "Photography studio",
      "Art gallery",
      "Museum",
      "Modern office",
      "Business district"
    ],

    vehicle: [
      "No vehicle",
      "Mercedes-Benz G-Wagon",
      "Mercedes-Benz S-Class",
      "Range Rover",
      "Range Rover Sport",
      "Lamborghini Urus",
      "Lamborghini Aventador",
      "Ferrari",
      "Porsche 911",
      "Bentley Continental",
      "Rolls-Royce",
      "BMW 7 Series",
      "BMW X7",
      "Audi Q8",
      "Cadillac Escalade",
      "Tesla Model S",
      "Tesla Model X",
      "Luxury SUV",
      "Luxury sports car",
      "Private jet",
      "Luxury yacht"
    ],

    store: [
      "No store",
      "Luxury fashion boutique",
      "Designer clothing store",
      "High-end shopping mall",
      "Premium department store",
      "Jewelry boutique",
      "Shoe boutique",
      "Designer handbag store",
      "Beauty store",
      "Cosmetics boutique",
      "Sports fashion store",
      "Streetwear store",
      "African fashion boutique",
      "Luxury lifestyle store",
      "Fashion showroom",
      "Designer showroom"
    ],

    lighting: [
      "Natural daylight",
      "Golden hour",
      "Soft studio lighting",
      "Luxury studio lighting",
      "Bright fashion lighting",
      "Cinematic lighting",
      "Warm evening light",
      "Sunset lighting",
      "Sunrise lighting",
      "Neon city lighting",
      "Night luxury lighting",
      "Soft window light",
      "Editorial lighting",
      "High-key fashion lighting",
      "Dramatic fashion lighting"
    ],

    imageFormat: [
      "Portrait — 1024 × 1536",
      "Landscape — 1536 × 1024",
      "Square — 1024 × 1024"
    ],

    camera: [
      "Professional fashion camera",
      "Full-body fashion photography",
      "Editorial photography",
      "Luxury campaign photography",
      "Magazine photography",
      "Cinematic photography",
      "Studio photography",
      "Street photography"
    ],

    mood: [
      "Luxury",
      "Elegant",
      "Confident",
      "Sophisticated",
      "Energetic",
      "Relaxed",
      "Glamorous",
      "Modern",
      "Powerful",
      "Romantic",
      "Professional",
      "Youthful"
    ]
  };

  // Extra compatibility for different versions of the OBITREND frontend
  const citiesByCountry = {
    Nigeria: ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Benin City", "Enugu", "Kano"],
    Ghana: ["Accra", "Kumasi", "Takoradi"],
    "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
    Egypt: ["Cairo", "Alexandria", "Giza", "Sharm El Sheikh"],
    Kenya: ["Nairobi", "Mombasa", "Kisumu"],
    Morocco: ["Marrakesh", "Casablanca", "Rabat", "Tangier"],
    "United States": ["New York", "Los Angeles", "Miami", "Las Vegas", "Chicago", "Atlanta"],
    "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool"],
    France: ["Paris", "Nice", "Lyon", "Marseille"],
    Italy: ["Milan", "Rome", "Florence", "Venice"],
    Spain: ["Barcelona", "Madrid", "Seville", "Valencia"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
    Qatar: ["Doha"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Dubai"],
    Turkey: ["Istanbul", "Antalya", "Ankara"],
    Greece: ["Athens", "Santorini", "Mykonos"],
    Brazil: ["Rio de Janeiro", "São Paulo"],
    Canada: ["Toronto", "Vancouver", "Montreal"],
    Australia: ["Sydney", "Melbourne", "Brisbane"],
    Japan: ["Tokyo", "Osaka", "Kyoto"],
    "South Korea": ["Seoul", "Busan"],
    Singapore: ["Singapore"],
    Thailand: ["Bangkok", "Phuket"],
    Switzerland: ["Zurich", "Geneva"],
    Germany: ["Berlin", "Munich", "Frankfurt"]
  };

  const response = {
    ...options,
    citiesByCountry
  };

  // Supports both older and newer OBITREND frontend versions
  response.options = response;

  return res.status(200).json(response);
}
